// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SustainabilityPlatform.Data;

#nullable disable

namespace SustainabilityPlatform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SustainabilityPlatform.Model.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplianceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplianceId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.Appliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplianceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplianceTypeId");

                    b.HasIndex("HomeId");

                    b.ToTable("Appliances");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.ApplianceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgEnergyRating")
                        .HasColumnType("float");

                    b.Property<double>("AvgWaterRating")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplianceTypes");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.EnergyUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplianceId")
                        .HasColumnType("int");

                    b.Property<double>("CostEstimate")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("KwhConsumed")
                        .HasColumnType("float");

                    b.Property<double>("PeakUsage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplianceId");

                    b.ToTable("EnergyUsages");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertId")
                        .HasColumnType("int");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.SensorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplianceId")
                        .HasColumnType("int");

                    b.Property<string>("ReadingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplianceId");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.SustainabilityScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("EnergyScore")
                        .HasColumnType("float");

                    b.Property<int>("HomeId")
                        .HasColumnType("int");

                    b.Property<double>("OverallScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<double>("WaterScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("SustainabilityScores");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.WaterUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplianceId")
                        .HasColumnType("int");

                    b.Property<double>("CostEstimate")
                        .HasColumnType("float");

                    b.Property<int>("CycleCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("LitersConsumed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplianceId");

                    b.ToTable("WaterUsages");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.Alert", b =>
                {
                    b.HasOne("SustainabilityPlatform.Model.Appliance", "Appliance")
                        .WithMany("Alerts")
                        .HasForeignKey("ApplianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appliance");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.Appliance", b =>
                {
                    b.HasOne("SustainabilityPlatform.Model.ApplianceType", "ApplianceType")
                        .WithMany("Appliances")
                        .HasForeignKey("ApplianceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SustainabilityPlatform.Model.Home", "Home")
                        .WithMany("Appliances")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplianceType");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.EnergyUsage", b =>
                {
                    b.HasOne("SustainabilityPlatform.Model.Appliance", "Appliance")
                        .WithMany("EnergyUsages")
                        .HasForeignKey("ApplianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appliance");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.Home", b =>
                {
                    b.HasOne("SustainabilityPlatform.Model.User", "User")
                        .WithMany("Homes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.Notification", b =>
                {
                    b.HasOne("SustainabilityPlatform.Model.Alert", "Alert")
                        .WithMany("Notifications")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SustainabilityPlatform.Model.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId");

                    b.Navigation("Alert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.SensorData", b =>
                {
                    b.HasOne("SustainabilityPlatform.Model.Appliance", "Appliance")
                        .WithMany("SensorData")
                        .HasForeignKey("ApplianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appliance");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.SustainabilityScore", b =>
                {
                    b.HasOne("SustainabilityPlatform.Model.Home", "Home")
                        .WithMany("SustainabilityScores")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.WaterUsage", b =>
                {
                    b.HasOne("SustainabilityPlatform.Model.Appliance", "Appliance")
                        .WithMany("WaterUsages")
                        .HasForeignKey("ApplianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appliance");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.Alert", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.Appliance", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("EnergyUsages");

                    b.Navigation("SensorData");

                    b.Navigation("WaterUsages");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.ApplianceType", b =>
                {
                    b.Navigation("Appliances");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.Home", b =>
                {
                    b.Navigation("Appliances");

                    b.Navigation("SustainabilityScores");
                });

            modelBuilder.Entity("SustainabilityPlatform.Model.User", b =>
                {
                    b.Navigation("Homes");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
